name: Compare garbage collectors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "pro-customer-image"
      APP_PORT: 8080
      G1GC_PARAMS: "-XX:+UseG1GC"
      ZGC_PARAMS: "-XX:+UseZGC"

    steps:
      #checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build the JAR file
        run: ./gradlew build

      # Set up Docker and Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Set up Docker Compose
      - name: Start services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 20 # Wait for services to start

      #build docker image of pro-customer app
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      #Run application with G1GC
      - name: Run Application with G1GC
        run: |
          docker run -d --name pro-customer-g1gc -p $APP_PORT:8080 $IMAGE_NAME java $G1GC_PARAMS -jar build/libs/procustomer-0.0.1-SNAPSHOT.jar
        id: g1gc-app

        #install newman to test api
      - name: Install Newman
        run: npm install -g newman

        #Run postman tests(G1GC)
      - name: Run Postman tests
        run: |
          newman run postman-collection/NimbusPay-ProCustomer.postman_collection.json \
          -r json --reporter-json-export results/g1gc_results.json --verbose
        id: g1gc-test

        #Stop G1GC container
      - name: Stop G1GC Container
        run: docker stop g1gc-app && docker rm g1gc-app

        #Run application with ZGC
      - name: Run Application With ZGC
        run: |
          docker run -d --name pro-customer-zgc -p 8081:8080 $IMAGE_NAME java $ZGC_PARAMS -jar build/libs/procustomer-0.0.1-SNAPSHOT.jar
        id: zgc-app

        #Run Postman test(ZGC)
      - name: Run Postman tests
        run: |
          newman run postman-collection/NimbusPay-ProCustomer.postman_collection \
          -e postman-collection/NimbusPay-ProCustomer.postman_collection \
          -r json --reporter-json-export results/zgc_results.json
        id: zgc-test

        #Stop G1GC container
      - name: Stop ZGC Container
        run: docker stop zgc-app && docker rm zgc-app

      # Tear down services after tests
      - name: Tear down services
        run: docker-compose -f docker-compose.yml down

        #Pulish Test Results
      - name: Publish Test Results to Github Packages
        uses: actions/upload-artifact@v3
        with:
          name: gc-comparison-results

