name: Compare garbage collectors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "pro-customer-image"
      APP_PORT: 8080
      G1GC_PARAMS: "-XX:+UseG1GC"
      ZGC_PARAMS: "-XX:+UseZGC"

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build the JAR file
        run: ./gradlew build

      # Set up Docker and Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Start only Postgres service using Docker Compose
      - name: Start Postgres service using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d postgres
          sleep 20 # Wait for postgres to start

      # Build Docker image of pro-customer app
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      # Install K6
      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6

      # Run application with G1GC
      - name: Run Application with G1GC
        run: |
          docker run -d --name pro-customer-g1gc -p $APP_PORT:8080 $IMAGE_NAME java $G1GC_PARAMS -jar build/libs/procustomer-0.0.1-SNAPSHOT.jar
        id: g1gc-app

      # Run K6 tests (G1GC)
      - name: Run K6 tests for G1GC
        run: |
          k6 run --out json=g1gc_results.json k6-test-script.js
        id: g1gc-test

      # Stop G1GC container
      - name: Stop G1GC Container
        run: docker stop g1gc-app && docker rm g1gc-app

      # Run application with ZGC
      - name: Run Application with ZGC
        run: |
          docker run -d --name pro-customer-zgc -p 8081:8080 $IMAGE_NAME java $ZGC_PARAMS -jar build/libs/procustomer-0.0.1-SNAPSHOT.jar
        id: zgc-app

      # Run K6 tests (ZGC)
      - name: Run K6 tests for ZGC
        run: |
          k6 run --out json=zgc_results.json k6-test-script.js
        id: zgc-test

      # Stop ZGC container
      - name: Stop ZGC Container
        run: docker stop zgc-app && docker rm zgc-app

      # Tear down services after tests
      - name: Tear down services
        run: docker-compose -f docker-compose.yml down

      # Publish Test Results
      - name: Publish Test Results to Github Packages
        uses: actions/upload-artifact@v3
        with:
          name: gc-comparison-results
          path: |
            g1gc_results.json
            zgc_results.json
