name: Compare garbage collectors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: "pro-customer-image"
      APP_PORT: 8080
      G1GC_PARAMS: "-XX:+UseG1GC"
      ZGC_PARAMS: "-XX:+UseZGC"

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Make Gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build the JAR file
      - name: Build the JAR file
        run: ./gradlew build

      # Set up Docker and Docker Compose
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Start only Postgres service using Docker Compose
      - name: Start Postgres service using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d postgres
          sleep 20 # Wait for Postgres to start

      # Build Docker image of pro-customer app
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Create Docker Network
        run: docker network create test-network

      # Run application with G1GC
      - name: Run Application with G1GC
        run: |
          docker run -d --name pro-customer --network test-network -p 8080:8080 $IMAGE_NAME java $G1GC_PARAMS -jar build/libs/procustomer-0.0.1-SNAPSHOT.jar
        id: g1gc-app

      # Pull Newman Docker Image
      - name: Pull Newman Docker Image
        run: docker pull postman/newman

      # Run Postman tests using Newman Docker image (G1GC)
      - name: Run Postman Tests (G1GC)
        run: |
          docker run --network test-network -v $(pwd)/postman-collection:/etc/newman -t postman/newman run http://pro-customer-g1gc:8080/NimbusPay-ProCustomer.postman_collection.json --reporter-json-export /etc/newman/g1gc_results.json
        id: g1gc-test

      # Stop G1GC container
      - name: Stop G1GC Container
        run: docker stop g1gc-app && docker rm g1gc-app

      # Run application with ZGC
      - name: Run Application with ZGC
        run: |
          docker run -d --name pro-customer-zgc --network test-network -p 8081:8080 $IMAGE_NAME java $ZGC_PARAMS -jar build/libs/procustomer-0.0.1-SNAPSHOT.jar
        id: zgc-app

      # Run Postman tests using Newman Docker image (ZGC)
      - name: Run Postman Tests (ZGC)
        run: |
          docker run --network test-network -v $(pwd)/postman-collection:/etc/newman -t postman/newman run http://pro-customer-zgc:8080/NimbusPay-ProCustomer.postman_collection.json --reporter-json-export /etc/newman/zgc_results.json
        id: zgc-test

      # Stop ZGC container
      - name: Stop ZGC Container
        run: docker stop zgc-app && docker rm zgc-app

      - name: Remove Docker Network
        run: docker network rm test-network

      # Tear down services after tests
      - name: Tear down services
        run: docker-compose -f docker-compose.yml down

      # Publish Test Results
      - name: Publish Test Results to GitHub Packages
        uses: actions/upload-artifact@v3
        with:
          name: gc-comparison-results
          path: results/
